import express from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import XLSX from 'xlsx';
const { Pool } = require('pg');
import { randomUUID } from 'crypto';
import fs from 'fs';
import path from 'path';

const envFile = path.join(process.cwd(), '.env');
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^['"]|['"]$/g, '');
  }
}

type Role = 'SUPER_ADMIN' | 'TRANSPORT_ADMIN' | 'DISPATCHER' | 'DRIVER' | 'EMPLOYEE';
const app = express();
const PORT = Number(process.env.PORT || 5000);
const SECRET = process.env.JWT_SECRET || 'rideops-change-this-secret';
const CLIENT_ORIGIN = process.env.CLIENT_ORIGIN || 'http://localhost:5173';
const DATABASE_URL = process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/rideops';
const pool = new Pool({ connectionString: DATABASE_URL, max: Number(process.env.DB_POOL_SIZE || 20), ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : undefined });
app.use(cors({ origin: CLIENT_ORIGIN.split(',')[0].trim(), credentials: true }));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));

const schemaPath = path.join(process.cwd(), '..', 'database', 'schema.sql');
const schemaFallback = path.join(process.cwd(), 'database', 'schema.sql');

const clean = (v: any) => v === undefined || v === null ? '' : String(v).trim();
const iso = (v: any) => v ? new Date(v).toISOString() : null;
const haversine = (a: any, b: any) => { const R=6371000, rad=(x:number)=>x*Math.PI/180, dLat=rad(b.lat-a.lat), dLon=rad(b.lng-a.lng); const q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2; return 2*R*Math.asin(Math.sqrt(q)); };

async function q<T=any>(text:string, values:any[]=[]):Promise<T[]> { const r=await pool.query(text, values); return r.rows as T[]; }
async function one<T=any>(text:string, values:any[]=[]):Promise<T|undefined> { const r=await pool.query(text, values); return r.rows[0] as T|undefined; }
async function tx<T>(fn:(c:any)=>Promise<T>):Promise<T>{const c=await pool.connect();try{await c.query('BEGIN');const out=await fn(c);await c.query('COMMIT');return out}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

function auth(req:any,res:any,next:any){ const h=String(req.headers.authorization||''); if(!h.startsWith('Bearer ')) return res.status(401).json({message:'Authorization required'}); try{req.user=jwt.verify(h.slice(7),SECRET); next();}catch{return res.status(401).json({message:'Invalid or expired token'});} }
function canManage(role:Role){return ['SUPER_ADMIN','TRANSPORT_ADMIN','DISPATCHER'].includes(role)}
function requireManager(req:any,res:any){if(!canManage(req.user.role)) {res.status(403).json({message:'Permission denied'});return false}return true}
function normalizeEmployee(x:any){return {employeeCode:clean(x.employeeCode||x.EmployeeCode||x['Employee ID']),name:clean(x.name||x.Name||x.employeeName||x['Employee Name']),email:clean(x.email||x.Email).toLowerCase(),phone:clean(x.phone||x.Phone||x.mobile||x.Mobile),department:clean(x.department||x.Department),gender:(clean(x.gender||x.Gender||x.sex||x.Sex).toUpperCase()||'UNKNOWN'),pickup:clean(x.pickup||x.Pickup||x['Pickup Location']),drop:clean(x.drop||x.Drop||x['Drop Location']),status:clean(x.status||x.Status)||'ACTIVE'}}
function normalizeDriver(x:any){return {driverCode:clean(x.driverCode||x.DriverCode||x.driver_id||x['Driver ID']),name:clean(x.name||x.Name||x.driverName||x['Driver Name']),email:clean(x.email||x.Email).toLowerCase(),phone:clean(x.phone||x.Phone||x.mobile||x.Mobile),licenseNo:clean(x.licenseNo||x.LicenseNo||x['License No']),vehicleNo:clean(x.vehicleNo||x.VehicleNo||x['Vehicle Number']),vehicleType:clean(x.vehicleType||x.VehicleType||x['Vehicle Type'])||'Sedan',status:clean(x.status||x.Status)||'AVAILABLE'}}

async function audit(userId:string, action:string, entity:string, entityId:string, details:any={}) { await q('INSERT INTO audit_logs(id,user_id,action,entity,entity_id,details) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),userId,action,entity,entityId,details]); }
async function getUser(id:string){return one<any>('SELECT * FROM users WHERE id=$1',[id]);}
async function getEmployeeForUser(u:any){return one<any>('SELECT * FROM employees WHERE user_id=$1 OR lower(email)=lower($2) LIMIT 1',[u.id,u.email]);}
async function getDriverForUser(u:any){return one<any>('SELECT * FROM drivers WHERE user_id=$1 OR lower(email)=lower($2) LIMIT 1',[u.id,u.email]);}
function mapEmployee(r:any){return r&&{id:r.id,userId:r.user_id,employeeCode:r.employee_code,name:r.name,email:r.email,phone:r.phone,department:r.department,gender:r.gender,pickup:r.pickup_address,drop:r.drop_address,status:r.status,createdAt:iso(r.created_at)}}
function mapDriver(r:any){return r&&{id:r.id,userId:r.user_id,driverCode:r.driver_code,name:r.name,email:r.email,phone:r.phone,licenseNo:r.license_no,vehicleNo:r.vehicle_no,vehicleType:r.vehicle_type,status:r.status,currentLat:r.current_lat,currentLng:r.current_lng,lastSeenAt:iso(r.last_seen_at),createdAt:iso(r.created_at)}}
function mapVehicle(r:any){return {id:r.id,vehicleNo:r.vehicle_no,vehicleType:r.vehicle_type,capacity:r.capacity,status:r.status,driverId:r.driver_id,make:r.make,model:r.model,fuelType:r.fuel_type,insuranceExpiry:r.insurance_expiry,fitnessExpiry:r.fitness_expiry}}
function mapVendor(r:any){return {id:r.id,name:r.name,contact:r.contact,email:r.email,vehicles:r.vehicle_count,status:r.status,sla:r.sla}}
function mapShift(r:any){return {id:r.id,name:r.name,start:r.start_time,end:r.end_time,employees:r.employee_count,status:r.status}}
function mapRoute(r:any){return {id:r.id,name:r.name,direction:r.direction,stops:r.stops||[],distanceKm:Number(r.distance_km||0),estimatedMin:Number(r.estimated_min||0),status:r.status}}
function mapAlert(r:any){return {id:r.id,type:r.type,severity:r.severity,tripId:r.trip_id,employeeId:r.employee_id,driverId:r.driver_id,message:r.message,status:r.status,createdAt:iso(r.created_at),resolvedAt:iso(r.resolved_at)}}

async function enrichRide(r:any, role:Role){
  const e=await one<any>('SELECT * FROM employees WHERE id=$1',[r.employee_id]); const d=await one<any>('SELECT * FROM drivers WHERE id=$1',[r.driver_id]);
  const gps=await one<any>('SELECT count(*)::int AS count FROM gps_logs WHERE trip_id=$1',[r.id]);
  const last=await one<any>('SELECT * FROM gps_logs WHERE trip_id=$1 ORDER BY server_time DESC LIMIT 1',[r.id]);
  const events=await q<any>('SELECT id,event_type,occurred_at,route_order,gps_log_id,note FROM trip_events WHERE trip_id=$1 ORDER BY occurred_at',[r.id]);
  return {id:r.id,employeeId:r.employee_id,driverId:r.driver_id,pickup:r.pickup_address,drop:r.drop_address,scheduledAt:iso(r.scheduled_at),status:r.status,tripType:r.trip_type,passengers:r.passengers,note:r.note,otp:role==='EMPLOYEE'?r.otp:undefined,otpVerified:!!r.otp_verified_at,otpVerifiedAt:iso(r.otp_verified_at),employeeConfirmed:!!r.employee_confirmed_at,driverAccepted:!!r.driver_accepted_at,startedAt:iso(r.started_at),completedAt:iso(r.completed_at),pickedUpAt:iso(r.picked_up_at),droppedAt:iso(r.dropped_at),routeOrder:r.route_order,routeId:r.route_id,createdAt:iso(r.created_at),events:events.map(x=>({id:x.id,event:x.event_type,at:iso(x.occurred_at),routeOrder:x.route_order,gpsLogId:x.gps_log_id,note:x.note})),employeeName:e?.name||'Unknown',employeeCode:e?.employee_code||'',employeeGender:e?.gender||'',employeePhone:e?.phone||'',driverName:d?.name||'Unassigned',driverCode:d?.driver_code||'',driverPhone:d?.phone||'',vehicleNo:d?.vehicle_no||'',vehicleType:d?.vehicle_type||'',gpsCount:Number(gps?.count||0),lastGps:last?mapGps(last):null};
}
function mapGps(g:any){return {id:g.id,sequence:Number(g.sequence_no||0),tripId:g.trip_id,routeId:g.route_id,driverId:g.driver_id,employeeId:g.employee_id,lat:Number(g.lat),lng:Number(g.lng),accuracy:g.accuracy,speed:g.speed,bearing:g.bearing,altitude:g.altitude,batteryLevel:g.battery_level,networkType:g.network_type,provider:g.provider,deviceTime:iso(g.device_time),serverTime:iso(g.server_time),event:g.event,distanceFromPreviousMeters:g.distance_from_previous_meters}}

async function ensureDatabase(){
  const file=fs.existsSync(schemaPath)?schemaPath:schemaFallback;
  await pool.query(fs.readFileSync(file,'utf8'));
  const count=await one<any>('SELECT count(*)::int AS n FROM users');
  if(Number(count?.n||0)===0){
    const seedPath=path.join(process.cwd(),'..','database','seed.sql');
    const seedFallback=path.join(process.cwd(),'database','seed.sql');
    const seedFile=fs.existsSync(seedPath)?seedPath:seedFallback;
    if(fs.existsSync(seedFile)) await pool.query(fs.readFileSync(seedFile,'utf8'));
  }
}

app.get('/api/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,database:'postgresql',time:new Date().toISOString()})}catch(e:any){res.status(503).json({ok:false,database:'postgresql',message:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const email=clean(req.body?.email).toLowerCase(),password=String(req.body?.password??'');const u=await one<any>('SELECT * FROM users WHERE lower(email)=lower($1) AND password_hash=$2',[email,password]);if(!u)return res.status(401).json({message:'Invalid credentials. Check email and password.'});const token=jwt.sign({id:u.id,role:u.role,name:u.name,email:u.email},SECRET,{expiresIn:'12h'});res.json({token,user:{id:u.id,email:u.email,role:u.role,name:u.name},employee:mapEmployee(await getEmployeeForUser(u)),driver:mapDriver(await getDriverForUser(u))})}catch(e:any){res.status(500).json({message:e.message})}});
app.get('/api/auth/demo-users',async(req,res)=>res.json((await q<any>('SELECT id,email,role,name FROM users ORDER BY id')).map(u=>({...u,password:'admin123'}))));
app.get('/api/me',auth,async(req,res)=>{const u=await getUser(req.user.id);res.json({user:u?{id:u.id,email:u.email,role:u.role,name:u.name}:req.user,employee:mapEmployee(await getEmployeeForUser(req.user)),driver:mapDriver(await getDriverForUser(req.user))})});

app.get('/api/dashboard',auth,async(req,res)=>{try{let where='',params:any[]=[];if(req.user.role==='EMPLOYEE'){const e=await getEmployeeForUser(req.user);where=' WHERE employee_id=$1';params=[e?.id||'']}else if(req.user.role==='DRIVER'){const d=await getDriverForUser(req.user);where=' WHERE driver_id=$1';params=[d?.id||'']}const [stats]=await q<any>(`SELECT (SELECT count(*) FROM employees) employees,(SELECT count(*) FROM drivers) drivers,(SELECT count(*) FROM drivers WHERE status IN ('AVAILABLE','ON_TRIP')) "activeDrivers",count(*) "tripsToday",count(*) FILTER(WHERE status='IN_PROGRESS') "liveTrips",count(*) FILTER(WHERE status='REQUESTED') requested,count(*) FILTER(WHERE status='ASSIGNED') assigned,count(*) FILTER(WHERE status='COMPLETED') completed,(SELECT count(*) FROM gps_logs WHERE trip_id IN (SELECT id FROM trips${where})) "gpsEvents" FROM trips${where}` ,params);res.json({role:req.user.role,...stats,employees:Number(stats.employees),drivers:Number(stats.drivers),activeDrivers:Number(stats.activeDrivers),tripsToday:Number(stats.tripsToday),liveTrips:Number(stats.liveTrips),requested:Number(stats.requested),assigned:Number(stats.assigned),completed:Number(stats.completed),gpsEvents:Number(stats.gpsEvents)})}catch(e:any){res.status(500).json({message:e.message})}});

app.get('/api/employees',auth,async(req,res)=>{const search=clean(req.query.search),page=Number(req.query.page)||1,pageSize=Math.min(100,Math.max(1,Number(req.query.pageSize)||25));let rows=await q<any>("SELECT * FROM employees WHERE ($1='' OR concat_ws(' ',employee_code,name,email,phone,department,gender,pickup_address,drop_address,status) ILIKE '%'||$1||'%') ORDER BY created_at DESC",[search]);rows=rows.map(mapEmployee);if(req.query.page===undefined&&req.query.pageSize===undefined&&req.query.search===undefined)return res.json(rows);const total=rows.length,start=(page-1)*pageSize;res.json({data:rows.slice(start,start+pageSize),total,page,pageSize,totalPages:Math.max(1,Math.ceil(total/pageSize))})});
app.post('/api/employees',auth,async(req,res)=>{if(!requireManager(req,res))return;try{const e=normalizeEmployee(req.body);if(!e.name||!e.email||!e.phone||!e.pickup||!e.drop)return res.status(400).json({message:'Name, email, phone, pickup and drop are required'});if(await one('SELECT 1 FROM employees WHERE lower(email)=lower($1)',[e.email]))return res.status(409).json({message:'Employee email already exists'});const record=await tx(async c=>{const uid=randomUUID(),id=`EMP-${Date.now()}`;await c.query('INSERT INTO users(id,email,password_hash,role,name) VALUES($1,$2,$3,$4,$5)',[uid,e.email,'admin123','EMPLOYEE',e.name]);const r=await c.query('INSERT INTO employees(id,user_id,employee_code,name,email,phone,department,gender,pickup_address,drop_address,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[id,uid,e.employeeCode||`E${Date.now()}`,e.name,e.email,e.phone,e.department,e.gender,e.pickup,e.drop,e.status]);return r.rows[0]});await audit(req.user.id,'CREATE','EMPLOYEE',record.id,e);res.status(201).json(mapEmployee(record))}catch(e:any){res.status(500).json({message:e.message})}});
app.put('/api/employees/:id',auth,async(req,res)=>{if(!requireManager(req,res))return;try{const e=normalizeEmployee(req.body);const r=await one<any>('UPDATE employees SET employee_code=COALESCE(NULLIF($1,\'\'),employee_code),name=$2,email=$3,phone=$4,department=$5,gender=$6,pickup_address=$7,drop_address=$8,status=$9 WHERE id=$10 RETURNING *',[e.employeeCode,e.name,e.email,e.phone,e.department,e.gender,e.pickup,e.drop,e.status,req.params.id]);if(!r)return res.status(404).json({message:'Employee not found'});await q('UPDATE users SET email=$1,name=$2 WHERE id=$3',[e.email,e.name,r.user_id]);await audit(req.user.id,'UPDATE','EMPLOYEE',r.id,req.body);res.json(mapEmployee(r))}catch(e:any){res.status(500).json({message:e.message})}});
app.delete('/api/employees/:id',auth,async(req,res)=>{if(!requireManager(req,res))return;const r=await one<any>('DELETE FROM employees WHERE id=$1 RETURNING id,user_id',[req.params.id]);if(!r)return res.status(404).json({message:'Employee not found'});await q('DELETE FROM users WHERE id=$1',[r.user_id]);await audit(req.user.id,'DELETE','EMPLOYEE',r.id);res.json({message:'Employee deleted'})});
app.post('/api/employees/import',auth,async(req,res)=>{if(!requireManager(req,res))return;try{const raw=Buffer.from(String(req.body.fileBase64||'').replace(/^data:.*;base64,/,'') ,'base64');const wb=XLSX.read(raw,{type:'buffer'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});let added=0,skipped=0;for(const row of rows){const e=normalizeEmployee(row);if(!e.name||!e.email||!e.phone||!e.pickup||!e.drop||await one('SELECT 1 FROM employees WHERE lower(email)=lower($1)',[e.email])){skipped++;continue}await tx(async c=>{const uid=randomUUID();await c.query('INSERT INTO users(id,email,password_hash,role,name) VALUES($1,$2,$3,$4,$5)',[uid,e.email,'admin123','EMPLOYEE',e.name]);await c.query('INSERT INTO employees(id,user_id,employee_code,name,email,phone,department,gender,pickup_address,drop_address,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[`EMP-${Date.now()}-${added}`,uid,e.employeeCode||`E${Date.now()}-${added}`,e.name,e.email,e.phone,e.department,e.gender,e.pickup,e.drop,e.status]);});added++}await audit(req.user.id,'IMPORT','EMPLOYEE','BULK',{added,skipped});res.json({message:`${added} employees imported`,added,skipped})}catch(e:any){res.status(400).json({message:e.message})}});

app.get('/api/drivers',auth,async(req,res)=>{const search=clean(req.query.search),page=Number(req.query.page)||1,pageSize=Math.min(100,Math.max(1,Number(req.query.pageSize)||25));let rows=await q<any>("SELECT * FROM drivers WHERE ($1='' OR concat_ws(' ',driver_code,name,email,phone,license_no,vehicle_no,vehicle_type,status) ILIKE '%'||$1||'%') ORDER BY created_at DESC",[search]);rows=rows.map(mapDriver);if(req.query.page===undefined&&req.query.pageSize===undefined&&req.query.search===undefined)return res.json(rows);const total=rows.length,start=(page-1)*pageSize;res.json({data:rows.slice(start,start+pageSize),total,page,pageSize,totalPages:Math.max(1,Math.ceil(total/pageSize))})});
app.post('/api/drivers',auth,async(req,res)=>{if(!requireManager(req,res))return;try{const d=normalizeDriver(req.body);if(!d.name||!d.email||!d.phone||!d.licenseNo||!d.vehicleNo)return res.status(400).json({message:'Name, email, phone, license and vehicle are required'});if(await one('SELECT 1 FROM drivers WHERE lower(vehicle_no)=lower($1)',[d.vehicleNo]))return res.status(409).json({message:'Vehicle number already exists'});const r=await tx(async c=>{const uid=randomUUID(),id=`DRV-${Date.now()}`;await c.query('INSERT INTO users(id,email,password_hash,role,name) VALUES($1,$2,$3,$4,$5)',[uid,d.email,'admin123','DRIVER',d.name]);const x=await c.query('INSERT INTO drivers(id,user_id,driver_code,name,email,phone,license_no,vehicle_no,vehicle_type,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[id,uid,d.driverCode||`D${Date.now()}`,d.name,d.email,d.phone,d.licenseNo,d.vehicleNo,d.vehicleType,d.status]);return x.rows[0]});await audit(req.user.id,'CREATE','DRIVER',r.id,d);res.status(201).json(mapDriver(r))}catch(e:any){res.status(500).json({message:e.message})}});
app.put('/api/drivers/:id',auth,async(req,res)=>{if(!requireManager(req,res))return;try{const d=normalizeDriver(req.body),r=await one<any>('UPDATE drivers SET driver_code=COALESCE(NULLIF($1,\'\'),driver_code),name=$2,email=$3,phone=$4,license_no=$5,vehicle_no=$6,vehicle_type=$7,status=$8 WHERE id=$9 RETURNING *',[d.driverCode,d.name,d.email,d.phone,d.licenseNo,d.vehicleNo,d.vehicleType,d.status,req.params.id]);if(!r)return res.status(404).json({message:'Driver not found'});await q('UPDATE users SET email=$1,name=$2 WHERE id=$3',[d.email,d.name,r.user_id]);await audit(req.user.id,'UPDATE','DRIVER',r.id,req.body);res.json(mapDriver(r))}catch(e:any){res.status(500).json({message:e.message})}});
app.delete('/api/drivers/:id',auth,async(req,res)=>{if(!requireManager(req,res))return;const r=await one<any>('DELETE FROM drivers WHERE id=$1 RETURNING id,user_id',[req.params.id]);if(!r)return res.status(404).json({message:'Driver not found'});await q('DELETE FROM users WHERE id=$1',[r.user_id]);await audit(req.user.id,'DELETE','DRIVER',r.id);res.json({message:'Driver deleted'})});
app.post('/api/drivers/import',auth,async(req,res)=>{if(!requireManager(req,res))return;try{const raw=Buffer.from(String(req.body.fileBase64||'').replace(/^data:.*;base64,/,'') ,'base64');const wb=XLSX.read(raw,{type:'buffer'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});let added=0,skipped=0;for(const row of rows){const d=normalizeDriver(row);if(!d.name||!d.email||!d.phone||!d.licenseNo||!d.vehicleNo||await one('SELECT 1 FROM drivers WHERE lower(vehicle_no)=lower($1)',[d.vehicleNo])){skipped++;continue}await tx(async c=>{const uid=randomUUID();await c.query('INSERT INTO users(id,email,password_hash,role,name) VALUES($1,$2,$3,$4,$5)',[uid,d.email,'admin123','DRIVER',d.name]);await c.query('INSERT INTO drivers(id,user_id,driver_code,name,email,phone,license_no,vehicle_no,vehicle_type,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[`DRV-${Date.now()}-${added}`,uid,d.driverCode||`D${Date.now()}-${added}`,d.name,d.email,d.phone,d.licenseNo,d.vehicleNo,d.vehicleType,d.status]);});added++}await audit(req.user.id,'IMPORT','DRIVER','BULK',{added,skipped});res.json({message:`${added} drivers imported`,added,skipped})}catch(e:any){res.status(400).json({message:e.message})}});

app.get('/api/rides',auth,async(req,res)=>{let sql='SELECT * FROM trips',p:any[]=[];if(req.user.role==='EMPLOYEE'){const e=await getEmployeeForUser(req.user);sql+=' WHERE employee_id=$1';p=[e?.id||'']}else if(req.user.role==='DRIVER'){const d=await getDriverForUser(req.user);sql+=' WHERE driver_id=$1';p=[d?.id||'']}sql+=' ORDER BY COALESCE(route_order,999),created_at DESC';const rows=await q<any>(sql,p);res.json(await Promise.all(rows.map(r=>enrichRide(r,req.user.role))))});
app.post('/api/rides',auth,async(req,res)=>{try{let employeeId=clean(req.body.employeeId);if(req.user.role==='EMPLOYEE'){const e=await getEmployeeForUser(req.user);if(!e)return res.status(404).json({message:'Employee profile not found'});employeeId=e.id}const e=await one<any>('SELECT * FROM employees WHERE id=$1',[employeeId]);if(!e)return res.status(404).json({message:'Employee not found'});let driverId=clean(req.body.driverId)||null;if(driverId&&!canManage(req.user.role))driverId=null;if(driverId&&!await one('SELECT 1 FROM drivers WHERE id=$1',[driverId]))return res.status(404).json({message:'Selected driver not found'});const id=`TRIP-${Date.now()}-${Math.floor(Math.random()*1000)}`,scheduled=req.body.scheduledAt||new Date().toISOString(),routeId=driverId?`ROUTE-${driverId}-${new Date(scheduled).toISOString().slice(0,10)}`:null;const routeOrder=driverId?Number((await one<any>('SELECT count(*)::int n FROM trips WHERE driver_id=$1 AND route_id=$2',[driverId,routeId]))?.n||0)+1:null;const otp=String(Math.floor(100000+Math.random()*900000));const r=await one<any>('INSERT INTO trips(id,employee_id,driver_id,pickup_address,drop_address,scheduled_at,status,trip_type,passengers,note,otp,route_order,route_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *',[id,employeeId,driverId,clean(req.body.pickup||e.pickup_address),clean(req.body.drop||e.drop_address),scheduled,driverId?'ASSIGNED':'REQUESTED',clean(req.body.tripType)||'HOME_TO_OFFICE',Number(req.body.passengers||1),clean(req.body.note)||null,otp,routeOrder,routeId]);if(driverId)await q('UPDATE drivers SET status=\'ON_TRIP\' WHERE id=$1',[driverId]);await audit(req.user.id,'CREATE','RIDE',id,{employeeId,driverId});res.status(201).json(await enrichRide(r,req.user.role))}catch(e:any){res.status(500).json({message:e.message})}});
app.post('/api/rides/:id/otp',auth,async(req,res)=>{const r=await one<any>('SELECT * FROM trips WHERE id=$1',[req.params.id]),e=r&&await getEmployeeForUser(req.user);if(!r)return res.status(404).json({message:'Ride not found'});if(req.user.role!=='EMPLOYEE'||r.employee_id!==e?.id)return res.status(403).json({message:'Only the assigned employee can generate this OTP'});const otp=String(Math.floor(100000+Math.random()*900000));await q('UPDATE trips SET otp=$1 WHERE id=$2',[otp,r.id]);await audit(req.user.id,'GENERATE_OTP','RIDE',r.id);res.json({otp})});
app.post('/api/rides/:id/assign',auth,async(req,res)=>{if(!requireManager(req,res))return;const r=await one<any>('SELECT * FROM trips WHERE id=$1',[req.params.id]),d=await one<any>('SELECT * FROM drivers WHERE id=$1',[req.body.driverId]);if(!r||!d)return res.status(404).json({message:'Ride or driver not found'});const routeId=r.route_id||`ROUTE-${d.id}-${new Date(r.scheduled_at).toISOString().slice(0,10)}`;await tx(async c=>{await c.query('UPDATE trips SET driver_id=$1,status=\'ASSIGNED\',driver_accepted_at=NULL,route_id=$2 WHERE id=$3',[d.id,routeId,r.id]);const rows=await c.query('SELECT id FROM trips WHERE driver_id=$1 AND route_id=$2 ORDER BY scheduled_at,created_at',[d.id,routeId]);for(let i=0;i<rows.rows.length;i++)await c.query('UPDATE trips SET route_order=$1 WHERE id=$2',[i+1,rows.rows[i].id]);await c.query('UPDATE drivers SET status=\'ON_TRIP\' WHERE id=$1',[d.id]);});const rr=await one<any>('SELECT * FROM trips WHERE id=$1',[r.id]);await audit(req.user.id,'ASSIGN','RIDE',r.id,{driverId:d.id});res.json(await enrichRide(rr,req.user.role))});
app.post('/api/rides/:id/driver-accept',auth,async(req,res)=>{const r=await one<any>('SELECT * FROM trips WHERE id=$1',[req.params.id]),d=await getDriverForUser(req.user);if(!r||!d||r.driver_id!==d.id)return res.status(403).json({message:'Ride is not assigned to this driver'});const rr=await one<any>('UPDATE trips SET driver_accepted_at=now() WHERE id=$1 RETURNING *',[r.id]);await audit(req.user.id,'DRIVER_ACCEPT','RIDE',r.id);res.json(await enrichRide(rr,req.user.role))});
app.post('/api/rides/:id/employee-confirm',auth,async(req,res)=>{const r=await one<any>('SELECT * FROM trips WHERE id=$1',[req.params.id]),e=await getEmployeeForUser(req.user);if(!r||!e||r.employee_id!==e.id)return res.status(403).json({message:'This ride is not yours'});const rr=await one<any>('UPDATE trips SET employee_confirmed_at=now() WHERE id=$1 RETURNING *',[r.id]);await audit(req.user.id,'EMPLOYEE_CONFIRM','RIDE',r.id);res.json(await enrichRide(rr,req.user.role))});
app.get('/api/trip-records',auth,async(req,res)=>{let sql='SELECT * FROM trips',p:any[]=[];if(req.user.role==='EMPLOYEE'){const e=await getEmployeeForUser(req.user);sql+=' WHERE employee_id=$1';p=[e?.id||'']}else if(req.user.role==='DRIVER'){const d=await getDriverForUser(req.user);sql+=' WHERE driver_id=$1';p=[d?.id||'']}sql+=' ORDER BY created_at DESC';const rows=await q<any>(sql,p);res.json(await Promise.all(rows.map(r=>enrichRide(r,req.user.role))))});
app.post('/api/trips/:id/verify-otp',auth,async(req,res)=>{const r=await one<any>('SELECT * FROM trips WHERE id=$1',[req.params.id]),d=await getDriverForUser(req.user);if(!r||!d||r.driver_id!==d.id)return res.status(403).json({message:'Trip is not assigned to this driver'});if(String(req.body.otp||'')!==String(r.otp||''))return res.status(400).json({message:'Invalid employee OTP'});const rr=await one<any>('UPDATE trips SET otp_verified_at=now() WHERE id=$1 RETURNING *',[r.id]);await audit(req.user.id,'VERIFY_OTP','TRIP',r.id);res.json(await enrichRide(rr,req.user.role))});
app.post('/api/trips/:id/start',auth,async(req,res)=>{const r=await one<any>('SELECT * FROM trips WHERE id=$1',[req.params.id]);if(!r)return res.status(404).json({message:'Trip not found'});if(req.user.role==='DRIVER'){const d=await getDriverForUser(req.user);if(!d||r.driver_id!==d.id)return res.status(403).json({message:'Trip not assigned to this driver'});if(!r.otp_verified_at)return res.status(400).json({message:'Employee OTP must be verified first'});if(!r.driver_accepted_at)return res.status(400).json({message:'Driver must accept the assigned ride first'})}if(req.user.role==='EMPLOYEE'){const e=await getEmployeeForUser(req.user);if(!e||r.employee_id!==e.id)return res.status(403).json({message:'This ride is not yours'});if(!r.otp_verified_at)return res.status(400).json({message:'Driver has not verified your OTP yet'})}const rr=await one<any>('UPDATE trips SET status=\'IN_PROGRESS\',started_at=COALESCE(started_at,now()) WHERE id=$1 RETURNING *',[r.id]);await audit(req.user.id,'START_TRIP','TRIP',r.id);res.json(await enrichRide(rr,req.user.role))});
app.post('/api/trips/:id/complete',auth,async(req,res)=>{const r=await one<any>('SELECT * FROM trips WHERE id=$1',[req.params.id]);if(!r)return res.status(404).json({message:'Trip not found'});if(req.user.role==='DRIVER'){const d=await getDriverForUser(req.user);if(!d||r.driver_id!==d.id)return res.status(403).json({message:'Not your trip'})}if(req.user.role==='EMPLOYEE'){const e=await getEmployeeForUser(req.user);if(!e||r.employee_id!==e.id)return res.status(403).json({message:'Not your trip'})}const rr=await one<any>('UPDATE trips SET status=\'COMPLETED\',completed_at=now() WHERE id=$1 RETURNING *',[r.id]);if(r.driver_id&&!await one('SELECT 1 FROM trips WHERE driver_id=$1 AND id<>$2 AND status IN (\'ASSIGNED\',\'IN_PROGRESS\')',[r.driver_id,r.id]))await q('UPDATE drivers SET status=\'AVAILABLE\' WHERE id=$1',[r.driver_id]);await audit(req.user.id,'COMPLETE_TRIP','TRIP',r.id);res.json(await enrichRide(rr,req.user.role))});
app.post('/api/trips/:id/event',auth,async(req,res)=>{const r=await one<any>('SELECT * FROM trips WHERE id=$1',[req.params.id]);if(!r)return res.status(404).json({message:'Trip not found'});if(req.user.role==='DRIVER'){const d=await getDriverForUser(req.user);if(!d||r.driver_id!==d.id)return res.status(403).json({message:'Not your trip'})}const event=clean(req.body.event||'TRIP_EVENT').toUpperCase();if(event==='EMPLOYEE_DROPOFF'&&!r.picked_up_at)return res.status(400).json({message:'Pickup must be recorded before drop-off'});const last=await one<any>('SELECT id FROM gps_logs WHERE trip_id=$1 ORDER BY server_time DESC LIMIT 1',[r.id]);await q('INSERT INTO trip_events(id,trip_id,event_type,route_order,gps_log_id,note) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),r.id,event,r.route_order||null,last?.id||null,clean(req.body.note)||null]);if(event==='EMPLOYEE_PICKUP')await q('UPDATE trips SET picked_up_at=now() WHERE id=$1',[r.id]);if(event==='EMPLOYEE_DROPOFF')await q('UPDATE trips SET dropped_at=now() WHERE id=$1',[r.id]);const rr=await one<any>('SELECT * FROM trips WHERE id=$1',[r.id]);await audit(req.user.id,event,'TRIP',r.id);res.json(await enrichRide(rr,req.user.role))});

app.post('/api/trips/:id/gps',auth,async(req,res)=>{try{const r=await one<any>('SELECT * FROM trips WHERE id=$1',[req.params.id]);if(!r)return res.status(404).json({message:'Trip not found'});if(req.user.role==='DRIVER'){const d=await getDriverForUser(req.user);if(!d||r.driver_id!==d.id)return res.status(403).json({message:'Not your trip'})}else if(req.user.role==='EMPLOYEE'){const e=await getEmployeeForUser(req.user);if(!e||r.employee_id!==e.id)return res.status(403).json({message:'Not your trip'})}const lat=Number(req.body.lat),lng=Number(req.body.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return res.status(400).json({message:'Valid lat/lng required'});const prev=await one<any>('SELECT lat,lng FROM gps_logs WHERE trip_id=$1 ORDER BY server_time DESC LIMIT 1',[r.id]);const seq=Number((await one<any>('SELECT count(*)::bigint n FROM gps_logs WHERE trip_id=$1',[r.id]))?.n||0)+1;const p=await one<any>('INSERT INTO gps_logs(id,trip_id,route_id,driver_id,employee_id,lat,lng,accuracy,speed,bearing,altitude,battery_level,network_type,provider,device_time,event,sequence_no,distance_from_previous_meters) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) RETURNING *',[randomUUID(),r.id,r.route_id,r.driver_id,r.employee_id,lat,lng,Number(req.body.accuracy||0),Number(req.body.speed||0),Number(req.body.bearing||0),Number(req.body.altitude||0),req.body.batteryLevel??null,req.body.networkType||null,req.body.provider||'browser-geolocation',req.body.deviceTime||new Date().toISOString(),req.body.event||'GPS_PING',seq,prev?haversine(prev,{lat,lng}):0]);await q('UPDATE drivers SET current_lat=$1,current_lng=$2,last_seen_at=now() WHERE id=$3',[lat,lng,r.driver_id]);res.status(201).json(mapGps(p))}catch(e:any){res.status(500).json({message:e.message})}});
app.get('/api/trips/:id/gps',auth,async(req,res)=>{const r=await one<any>('SELECT * FROM trips WHERE id=$1',[req.params.id]);if(!r)return res.status(404).json({message:'Trip not found'});if(req.user.role==='EMPLOYEE'&&(await getEmployeeForUser(req.user))?.id!==r.employee_id)return res.status(403).json({message:'Not your trip'});if(req.user.role==='DRIVER'&&(await getDriverForUser(req.user))?.id!==r.driver_id)return res.status(403).json({message:'Not your trip'});res.json((await q<any>('SELECT * FROM gps_logs WHERE trip_id=$1 ORDER BY server_time',[r.id])).map(mapGps))});
app.get('/api/gps-logs',auth,async(req,res)=>{let sql='SELECT * FROM gps_logs',p:any[]=[];if(req.user.role==='EMPLOYEE'){const e=await getEmployeeForUser(req.user);sql+=' WHERE employee_id=$1';p=[e?.id||'']}if(req.user.role==='DRIVER'){const d=await getDriverForUser(req.user);sql+=' WHERE driver_id=$1';p=[d?.id||'']}sql+=' ORDER BY server_time DESC LIMIT 1000';res.json((await q<any>(sql,p)).map(mapGps))});
app.get('/api/live-tracking',auth,async(req,res)=>{let sql=`SELECT t.*,e.name employee_name,e.phone employee_phone,d.name driver_name,d.phone driver_phone,d.vehicle_no,d.vehicle_type,g.lat,g.lng,g.accuracy,g.speed,g.bearing,g.server_time,g.sequence_no FROM trips t JOIN employees e ON e.id=t.employee_id LEFT JOIN drivers d ON d.id=t.driver_id LEFT JOIN LATERAL (SELECT * FROM gps_logs WHERE trip_id=t.id ORDER BY server_time DESC LIMIT 1) g ON true WHERE t.status IN ('ASSIGNED','IN_PROGRESS')`,p:any[]=[];if(req.user.role==='EMPLOYEE'){const e=await getEmployeeForUser(req.user);sql+=' AND t.employee_id=$1';p=[e?.id||'']}if(req.user.role==='DRIVER'){const d=await getDriverForUser(req.user);sql+=' AND t.driver_id=$1';p=[d?.id||'']}const rows=await q<any>(sql,p);res.json({serverTime:new Date().toISOString(),count:rows.length,vehicles:rows.map(x=>({...x,id:x.id,employeeId:x.employee_id,driverId:x.driver_id,pickup:x.pickup_address,drop:x.drop_address,status:x.status,employeeName:x.employee_name,employeePhone:x.employee_phone||'',driverName:x.driver_name||'Unassigned',driverPhone:x.driver_phone||'',vehicleNo:x.vehicle_no||'',vehicleType:x.vehicle_type||'',lastGps:x.lat==null?null:{lat:Number(x.lat),lng:Number(x.lng),accuracy:x.accuracy,speed:x.speed,bearing:x.bearing,serverTime:iso(x.server_time),sequence:Number(x.sequence_no||0)},gpsOnline:!!x.server_time&&(Date.now()-new Date(x.server_time).getTime()<20000),gpsAgeSeconds:x.server_time?Math.max(0,Math.round((Date.now()-new Date(x.server_time).getTime())/1000)):null}))})});
app.get('/api/audit-logs',auth,async(req,res)=>res.json(await q<any>('SELECT id,user_id "userId",action,entity,entity_id "entityId",details,created_at "createdAt" FROM audit_logs ORDER BY created_at DESC LIMIT 1000')));

app.get('/api/fleet',auth,async(req,res)=>res.json((await q<any>('SELECT * FROM vehicles ORDER BY id')).map(mapVehicle)));
app.post('/api/fleet',auth,async(req,res)=>{if(!requireManager(req,res))return;try{const v={id:`VEH-${Date.now()}`,vehicleNo:clean(req.body.vehicleNo),vehicleType:clean(req.body.vehicleType)||'Sedan',capacity:Number(req.body.capacity||4),status:clean(req.body.status)||'AVAILABLE',driverId:clean(req.body.driverId)||null,make:clean(req.body.make),model:clean(req.body.model),fuelType:clean(req.body.fuelType)||'CNG',insuranceExpiry:clean(req.body.insuranceExpiry)||null,fitnessExpiry:clean(req.body.fitnessExpiry)||null};if(!v.vehicleNo)return res.status(400).json({message:'Vehicle number is required'});const r=await one<any>('INSERT INTO vehicles(id,vehicle_no,vehicle_type,capacity,status,driver_id,make,model,fuel_type,insurance_expiry,fitness_expiry) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',Object.values(v));await audit(req.user.id,'CREATE','VEHICLE',v.id,v);res.status(201).json(mapVehicle(r))}catch(e:any){res.status(409).json({message:e.message})}});
app.put('/api/fleet/:id',auth,async(req,res)=>{if(!requireManager(req,res))return;const v=req.body,r=await one<any>('UPDATE vehicles SET vehicle_no=COALESCE($1,vehicle_no),vehicle_type=COALESCE($2,vehicle_type),capacity=COALESCE($3,capacity),status=COALESCE($4,status),driver_id=$5,make=$6,model=$7,fuel_type=$8,insurance_expiry=$9,fitness_expiry=$10 WHERE id=$11 RETURNING *',[v.vehicleNo,v.vehicleType,v.capacity,v.status,v.driverId||null,v.make||null,v.model||null,v.fuelType||null,v.insuranceExpiry||null,v.fitnessExpiry||null,req.params.id]);if(!r)return res.status(404).json({message:'Vehicle not found'});await audit(req.user.id,'UPDATE','VEHICLE',r.id,v);res.json(mapVehicle(r))});
app.delete('/api/fleet/:id',auth,async(req,res)=>{if(!requireManager(req,res))return;const r=await one<any>('DELETE FROM vehicles WHERE id=$1 RETURNING id',[req.params.id]);if(!r)return res.status(404).json({message:'Vehicle not found'});res.json({message:'Vehicle deleted'})});

app.get('/api/vendors',auth,async(req,res)=>res.json((await q<any>('SELECT * FROM vendors ORDER BY id')).map(mapVendor)));
app.post('/api/vendors',auth,async(req,res)=>{if(!requireManager(req,res))return;const v={id:`VEN-${Date.now()}`,name:clean(req.body.name),contact:clean(req.body.contact),email:clean(req.body.email),vehicleCount:Number(req.body.vehicles||0),status:clean(req.body.status)||'ACTIVE',sla:clean(req.body.sla)||'95%'};if(!v.name)return res.status(400).json({message:'Vendor name is required'});const r=await one<any>('INSERT INTO vendors(id,name,contact,email,vehicle_count,status,sla) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',Object.values(v));res.status(201).json(mapVendor(r))});
app.put('/api/vendors/:id',auth,async(req,res)=>{if(!requireManager(req,res))return;const v=req.body,r=await one<any>('UPDATE vendors SET name=COALESCE($1,name),contact=$2,email=$3,vehicle_count=$4,status=$5,sla=$6 WHERE id=$7 RETURNING *',[v.name,v.contact,v.email,Number(v.vehicles||0),v.status||'ACTIVE',v.sla||'95%',req.params.id]);if(!r)return res.status(404).json({message:'Vendor not found'});res.json(mapVendor(r))});
app.get('/api/shifts',auth,async(req,res)=>res.json((await q<any>('SELECT * FROM shifts ORDER BY id')).map(mapShift)));
app.post('/api/shifts',auth,async(req,res)=>{if(!requireManager(req,res))return;const x={id:`SFT-${Date.now()}`,name:clean(req.body.name),start:clean(req.body.start),end:clean(req.body.end),employeeCount:Number(req.body.employees||0),status:'ACTIVE'};if(!x.name||!x.start||!x.end)return res.status(400).json({message:'Shift name, start and end are required'});const r=await one<any>('INSERT INTO shifts(id,name,start_time,end_time,employee_count,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',Object.values(x));res.status(201).json(mapShift(r))});
app.get('/api/routes',auth,async(req,res)=>res.json((await q<any>('SELECT * FROM service_routes ORDER BY id')).map(mapRoute)));
app.post('/api/routes',auth,async(req,res)=>{if(!requireManager(req,res))return;const x={id:`RTE-${Date.now()}`,name:clean(req.body.name),direction:clean(req.body.direction)||'OFFICE',stops:Array.isArray(req.body.stops)?req.body.stops:String(req.body.stops||'').split(',').map((z:string)=>z.trim()).filter(Boolean),distanceKm:Number(req.body.distanceKm||0),estimatedMin:Number(req.body.estimatedMin||0),status:'ACTIVE'};if(!x.name||!x.stops.length)return res.status(400).json({message:'Route name and stops are required'});const r=await one<any>('INSERT INTO service_routes(id,name,direction,stops,distance_km,estimated_min,status) VALUES($1,$2,$3,$4::jsonb,$5,$6,$7) RETURNING *',[x.id,x.name,x.direction,JSON.stringify(x.stops),x.distanceKm,x.estimatedMin,x.status]);res.status(201).json(mapRoute(r))});
app.get('/api/safety-alerts',auth,async(req,res)=>res.json((await q<any>('SELECT * FROM safety_alerts ORDER BY created_at DESC LIMIT 500')).map(mapAlert)));
app.post('/api/safety-alerts',auth,async(req,res)=>{const x={id:`ALT-${Date.now()}`,type:clean(req.body.type)||'SOS',severity:clean(req.body.severity)||'HIGH',tripId:clean(req.body.tripId)||null,employeeId:clean(req.body.employeeId)||null,driverId:clean(req.body.driverId)||null,message:clean(req.body.message)||'Emergency assistance requested',status:'OPEN'};const r=await one<any>('INSERT INTO safety_alerts(id,type,severity,trip_id,employee_id,driver_id,message,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',Object.values(x));await q('INSERT INTO notifications(id,type,message) VALUES($1,$2,$3)',[`NTF-${Date.now()}`,'SAFETY',x.message]);await audit(req.user.id,'SAFETY_ALERT','ALERT',x.id,x);res.status(201).json(mapAlert(r))});
app.post('/api/safety-alerts/:id/resolve',auth,async(req,res)=>{if(!requireManager(req,res))return;const r=await one<any>('UPDATE safety_alerts SET status=\'RESOLVED\',resolved_at=now() WHERE id=$1 RETURNING *',[req.params.id]);if(!r)return res.status(404).json({message:'Alert not found'});res.json(mapAlert(r))});
app.get('/api/reports/summary',auth,async(req,res)=>{const [r]=await q<any>(`SELECT (SELECT count(*) FROM employees)::int employees,(SELECT count(*) FROM drivers)::int drivers,(SELECT count(*) FROM vehicles)::int vehicles,(SELECT count(*) FROM vendors)::int vendors,(SELECT count(*) FROM shifts)::int shifts,(SELECT count(*) FROM service_routes)::int routes,(SELECT count(*) FROM trips)::int "totalTrips",(SELECT count(*) FROM trips WHERE status='COMPLETED')::int completed,(SELECT count(*) FROM trips WHERE status='CANCELLED')::int cancelled,(SELECT count(*) FROM trips WHERE status IN ('ASSIGNED','IN_PROGRESS'))::int active,(SELECT count(*) FROM safety_alerts WHERE status='OPEN')::int "openAlerts",(SELECT count(*) FROM gps_logs)::int "gpsPoints",COALESCE((SELECT sum(distance_from_previous_meters)/1000 FROM gps_logs),0) "totalDistanceKm"`);res.json(r)});
app.get('/api/notifications',auth,async(req,res)=>res.json(await q<any>('SELECT id,type,message,created_at "createdAt",read FROM notifications ORDER BY created_at DESC LIMIT 100')));

function serverKey(){return process.env.GOOGLE_MAPS_SERVER_API_KEY||''}
async function googleFetch(url:string,body:any,extra:any={}){const key=serverKey();if(!key)throw new Error('GOOGLE_MAPS_SERVER_API_KEY is not configured');const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key,...extra},body:JSON.stringify(body)});const t=await r.text();let j:any;try{j=JSON.parse(t)}catch{j={raw:t}}if(!r.ok)throw new Error(j.error?.message||`Google API ${r.status}`);return j}
app.get('/api/maps/config',auth,(req,res)=>res.json({browserApiKey:process.env.GOOGLE_MAPS_BROWSER_API_KEY||'',mapId:process.env.GOOGLE_MAPS_MAP_ID||'DEMO_MAP_ID'}));
app.post('/api/maps/geocode',auth,async(req,res)=>{try{const key=serverKey();if(!key)throw new Error('Server Google key is not configured');const u=new URL('https://maps.googleapis.com/maps/api/geocode/json');u.searchParams.set('address',String(req.body.address||''));u.searchParams.set('key',key);const r=await fetch(u);res.status(r.ok?200:502).json(await r.json())}catch(e:any){res.status(500).json({message:e.message})}});
app.post('/api/maps/reverse-geocode',auth,async(req,res)=>{try{const key=serverKey();if(!key)throw new Error('Server Google key is not configured');const u=new URL('https://maps.googleapis.com/maps/api/geocode/json');u.searchParams.set('latlng',`${req.body.lat},${req.body.lng}`);u.searchParams.set('key',key);const r=await fetch(u);res.status(r.ok?200:502).json(await r.json())}catch(e:any){res.status(500).json({message:e.message})}});
app.post('/api/maps/places/autocomplete',auth,async(req,res)=>{try{const key=serverKey();if(!key)throw new Error('Server Google key is not configured');const r=await fetch('https://places.googleapis.com/v1/places:autocomplete',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key},body:JSON.stringify({input:String(req.body.input||''),includedRegionCodes:['in']})});res.status(r.ok?200:502).json(await r.json())}catch(e:any){res.status(500).json({message:e.message})}});
app.post('/api/maps/places/details',auth,async(req,res)=>{try{const key=serverKey();if(!key)throw new Error('Server Google key is not configured');const id=String(req.body.placeId||'');const r=await fetch(`https://places.googleapis.com/v1/places/${encodeURIComponent(id)}`,{headers:{'X-Goog-Api-Key':key,'X-Goog-FieldMask':'id,displayName,formattedAddress,location'}});res.status(r.ok?200:502).json(await r.json())}catch(e:any){res.status(500).json({message:e.message})}});
app.post('/api/maps/address-validation',auth,async(req,res)=>{try{res.json(await googleFetch('https://addressvalidation.googleapis.com/v1:validateAddress',{address:{addressLines:[String(req.body.address||'')]}}))}catch(e:any){res.status(500).json({message:e.message})}});
app.post('/api/maps/route',auth,async(req,res)=>{try{res.json(await googleFetch('https://routes.googleapis.com/directions/v2:computeRoutes',{origin:{address:String(req.body.origin||'')},destination:{address:String(req.body.destination||'')},travelMode:'DRIVE',routingPreference:'TRAFFIC_AWARE',computeAlternativeRoutes:false,routeModifiers:{avoidTolls:false,avoidHighways:false,avoidFerries:false},languageCode:'en-US',units:'METRIC'},{'X-Goog-FieldMask':'routes.duration,routes.distanceMeters,routes.polyline.encodedPolyline,routes.legs'}))}catch(e:any){res.status(500).json({message:e.message})}});
app.post('/api/maps/route-matrix',auth,async(req,res)=>{try{const origins=(req.body.origins||[]).map((x:any)=>({waypoint:{address:String(x.address||x)}})),destinations=(req.body.destinations||[]).map((x:any)=>({waypoint:{address:String(x.address||x)}}));res.json(await googleFetch('https://routes.googleapis.com/distanceMatrix/v2:computeRouteMatrix',{origins,destinations,travelMode:'DRIVE',routingPreference:'TRAFFIC_AWARE'},{'X-Goog-FieldMask':'originIndex,destinationIndex,duration,distanceMeters,status,condition'}))}catch(e:any){res.status(500).json({message:e.message})}});
app.get('/api/export/:type',auth,async(req,res)=>{const type=req.params.type==='drivers'?'drivers':'employees';const rows=type==='drivers'?(await q<any>('SELECT driver_code "driverCode",name,email,phone,license_no "licenseNo",vehicle_no "vehicleNo",vehicle_type "vehicleType",status FROM drivers')):(await q<any>('SELECT employee_code "employeeCode",name,email,phone,department,gender,pickup_address pickup,drop_address drop,status FROM employees'));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,type);const out=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Disposition',`attachment; filename=${type}.xlsx`);res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(out)});

async function start(){try{await pool.query('SELECT 1');await ensureDatabase();app.listen(PORT,()=>console.log(`RideOps API running on http://localhost:${PORT} using PostgreSQL`));}catch(e){console.error('RideOps failed to start. PostgreSQL connection/schema error:',e);process.exit(1)}}
start();
